"""add courses table

Revision ID: 5b286c6a5bb9
Revises: a8ef86b23e0c
Create Date: 2026-09-22 17:06:40.072125

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5b286c6a5bb9"
down_revision: Union[str, Sequence[str], None] = "a8ef86b23e0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courses",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "level",
            sa.Enum("beginner", "intermediate", "advanced", name="course_level"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("draft", "published", "archived", name="course_status"),
            nullable=False,
        ),
        sa.Column("instructor_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["instructor_id"], ["users.id"], name=op.f("fk_courses_instructor_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_courses")),
    )
    op.create_index(op.f("ix_courses_instructor_id"), "courses", ["instructor_id"], unique=False)
    op.create_index(op.f("ix_courses_title"), "courses", ["title"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_courses_title"), table_name="courses")
    op.drop_index(op.f("ix_courses_instructor_id"), table_name="courses")
    op.drop_table("courses")
    # ### end Alembic commands ###
    # op.drop_table() does not drop the Postgres native enum types it depended on
    # (see docs/adr/0008.md) — left behind, they collide with the next
    # upgrade/downgrade cycle's CREATE TYPE.
    sa.Enum(name="course_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="course_level").drop(op.get_bind(), checkfirst=True)
